### ISSUE TITLE
Small issue on subtraction

### ISSUE THREAD

**Issue by takanuva** [pdonadeo/ocaml-lens#11]
The operator `-=` isn't working properly (should be easy to reproduce). On `lens.ml`, line 173:

```
let (-=) l v = _modify ((-) v) l
```

(This probably affects line 183 as well.)

The value being subtracted (`v`) is being used on the _left_ position on the subtraction, giving an incorrect result. Could be changed to, e.g., `((+) (-v))` or `(fun x -> x - v)`.

**Comment by pdonadeo** [comment]
Sorry for the delay, I missed the notification.

I'll fix and release ASAP.

**Comment by pdonadeo** [comment]
@takanuva 1.2.2 just released and I sent the pull request to the OPAM repository.
