### ISSUE TITLE
Latest version not available in opam

### ISSUE THREAD

**Issue by juanchanco** [pdonadeo/ocaml-lens#4]
The official opam repository doesn't seem to acknowledge the existence of version 1.1.0 (and thus the ppx extensions). Unfortunately, I'm not knowledgeable enough about opam to troubleshoot this.

**Comment by pdonadeo** [comment]
I totally forgot to update the OPAM repository. I'll fix it ASAP, tonight or in this weekend at the latest.

**Comment by pdonadeo** [comment]
Just submitted version 1.1.0 to the OPAM official repository.
