### ISSUE TITLE
Can't access generated submodule when building with Jbuilder

### ISSUE THREAD

**Issue by ghost** [pdonadeo/ocaml-lens#8]
When trying to open a module when generating with `[@@deriving lens { submodule = true }]` and building with Jbuilder ([example](https://gitlab.com/orbifx/logarion/blob/e74c864f6daa95415bc2a17ddd7a1299769dce74/src/core/meta.ml#L115)).

This code worked fine with _oasis_ + _ocamlbuild_.

**Comment by ghost** [comment]
In case it's relevant, the [jbuild file](https://gitlab.com/orbifx/logarion/blob/e74c864f6daa95415bc2a17ddd7a1299769dce74/src/core/jbuild).

**Comment by pdonadeo** [comment]
@orbifx I never used jbuilder, can you produce a minimal example? Meanwhile I'm reading the documentation.

**Comment by pdonadeo** [comment]
I tried a very simple example:
```ocaml
type person = {
  first_name : string;
  last_name : string;
  age : int;
} [@@deriving lens { submodule = true }]

let main () =
  let paolo = {
    first_name = "Paolo";
    last_name = "Donadeo";
    age = 24;
  } in

  let open Lens in
  let paolo' = age.set 42 paolo in
  Printf.printf "Correct age = %d\n%!" paolo'.age

let () = main ()
```
it works in the toplevel (utop) and with ocamlbuild, but no joy with jbuilder.

But I have a clue... maybe it's not possible at all, read this topic: [Is it currently possible to use ppx_deriving in a jbuilder project](https://discuss.ocaml.org/t/is-it-currently-possible-to-use-ppx-deriving-in-a-jbuilder-project/426)

**Comment by ghost** [comment]
Yeah, building used to work fine until I [switched Logarion](https://gitlab.com/orbifx/logarion/commit/5032c009b3aa1b11b0ce81a15932ea36e4a3b934) to Jbuilder.

I had to drop the dependency for now. I'd like to make it at least optional.

**Comment by pdonadeo** [comment]
@orbifx can I close this issue? You can reopen it later, when jbuilder will support ppx_* libraries, hopefully.

**Comment by ghost** [comment]
I hope it's not going to be that long. We should have Lens in OCaml in general and Jbuilder **looks like** it could become the de-facto.

**Comment by pdonadeo** [comment]
Ok, I'll keep the issue open. Please ping me when you see some advances in jbuilder.

**Comment by fare** [comment]
It looks like jbuilder requires you to use new-style `Ppx_driver.register_transformation`. See https://github.com/little-arhat/ppx_jsobject_conv/issues/4

**Comment by fare** [comment]
See my proposed solution in #9

**Comment by pdonadeo** [comment]
@fare thanks, this week end I'll review your patch. Sorry but I can't devote time before the end of this week.

**Comment by fare** [comment]
NB: I didn't touch the original build system that I don't understand and don't know how to test.

**Comment by pdonadeo** [comment]
My answer in #9
